# Generated by Django 5.1.1 on 2024-10-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_alter_bulletin_options_alter_comment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название!', max_length=255, verbose_name='Название')),
                ('price', models.PositiveIntegerField(default=0, help_text='Введите цену!', verbose_name='Цена')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара!', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания объявления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(help_text='Выберите объявление!', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bulletins.ad', verbose_name='Объявление'),
        ),
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
